### ISSUE TITLE
ในหน้าดูสรุปรวมให้ทำ favourite bookmarks ด้วยว่าโพสต์ไหนที่ติดตาม

### ISSUE THREAD

**Issue by SupakornNetsuwan** [SupakornNetsuwan/webpro-project#26]

**Comment by yyolradee** [comment]
ไม่ใช่ว่าทำไว้แล้วหรอ ที่เค้า fetch ไว้แล้ว
[![Screenshot-2566-05-20-at-20.16.26.md.png](https://img.pic.in.th/Screenshot-2566-05-20-at-20.16.26.md.png)](https://pic.in.th/image/z5gGh)
